### ISSUE TITLE
Trochę mało tych testów ;)

### ISSUE THREAD

**Issue by boczkas** [AdrianHarenczyk/XOGameProject#3]
https://github.com/AdrianHarenczyk/XOGameProject/blob/b0446cdcbb735726d7d78b261445d736ec3438fc/src/test/java/xogame/tests/TestGameState.java#L15

**Comment by AdrianHarenczyk** [comment]
Tak, testy są w drodze. Początkowe skupienie na szkielecie aplikacji. :)
